---
title: "Zadání"
---


**Vytvořte webovou prezenatci nějakého dílčího úkolu z vaší diplomové práce.**

---

**Požadavky**

Prezentace bude:

- takového rozsahu, aby o ní bylo možno cca 5-10 minut mluvit,
- bude kombinovat text, kód a grafiku
- bude začleněná do [tohoto](https://github.com/hanel/PED_web) github repozitáře


---

### Postup

0. Nainstalujte git
1. Vytvořte si účet na https://github.com/
2. Forkněte (tlačítko Fork) repo https://github.com/hanel/PED_web do svého repozitáře
3. Naklonujte své repo (tlačítko Clone or download) - zkopírujte adresu *.git
4. V Rstudiu založte nový projekt z Version Control a adresu *.git vložte
5. V Rstudiu pomocí tlačítka Pull repozitář stáhněte
6. Pomocí ctrl+shift+b sestavte web (nebo záložka Build)

7. V RStudiu vytvořte nový RMarkdown dokument
8. Pojmenujte ho např. vaším monogramem
9. Hlavičku nechte ve tvaru (název upravte)

```{}
---
title: "Váš název"
---

```

10. Do souboru napiště nějaký provizorní text
11. Editací souboru `_site.yml` začleňte vaši prezentaci do menu, tj. v části hlavičky

```{}
 - text: Prezentace
    menu:
    - text: Jan Petr
      href: jp.html
```

doplňte další odrážku `-text: Vaše jméno` a `href: odkaz_na_váš_soubor.html` (nezapomeňte, že přestože editujete soubor `odkaz_na_váš_soubor.Rmd`, zde se objeví již přeložený soubor `odkaz_na_váš_soubor.html`)

12. Projekt sestavte, v záložce Git zaregistrujte změny (Commit) - nezapomeňte přidat zprávu o tom, co jste udělali.
13. Pomocí tlačitka Push projekt nahrajte na github
14. Na githubu vytvořte nový pull request 

15. Kroky 12-13 průběžně opakujte, pokud budete chtít pracovat s repozitářem na jiném počítači, můžete jej synchronizovat pomocí tlačítka pull

16. Dodělejte svou stránku

17. Na hlavní stránce (`index.Rmd`) doplňte Vaše jméno, nějaký reprezentativní obrázek a abstrakt k vaší práci 

18. Pushněte na github a vytvořte pull request

* Pokud chcete synchronizovat svůj repozitář s původním repozitářem (https://github.com/hanel/PED_web), do kterého možná již přispěli vaši spolužáci, použijte následující skript

```{r eval=FALSE, echo = -2, eval = -3}
# library(git2r)
# repo = repository('')
# repo = repository('cesta_k_vasemu_repozitari_v_pocitaci')
# remote_add(repo)
```

